site_name: Knowledge Base
site_url: https://sitename.example
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.instant.progress # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=breadcrumbs#progress-indicator
    - navigation.instant.preview # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=breadcrumbs#automatic-previews
    - navigation.sections # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    - navigation.tracking # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=breadcrumbs#anchor-tracking
    - navigation.prune # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=breadcrumbs#navigation-pruning
    - navigation.top # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=breadcrumbs#back-to-top-button
  font: 
    text: Quicksand
  palette:
    scheme: slate
  plugins:
    - search
    - material-extensions
nav:
  - <i class="hgi-stroke hgi-book-open-01"></i> Start Here:
    - start-here/index.md
    - Glossary: glossary/index.md
  - <i class="hgi-stroke hgi-user"></i> Digital Accounts:
    - <i class="hgi-stroke hgi-signature"></i> Creation: digital-accounts/creation/index.md
    - <i class="hgi-stroke hgi-authorized"></i> Authentication: digital-accounts/authentication/index.md
  - <i class="hgi-stroke hgi-cloud"></i> Getting Online:
    - <i class="hgi-stroke hgi-corporate"></i> Service Providers: getting-online/service-providers/index.md
    - <i class="hgi-stroke hgi-internet-antenna-03"></i> Long Range Antennas: getting-online/hardware/long-range-antennas/index.md
    - <i class="hgi-stroke hgi-router-02"></i> Gateways: getting-online/hardware/gateways/index.md
    - <i class="hgi-stroke hgi-wifi-lock"></i> Access Points: getting-online/hardware/access-points/index.md
    - <i class="hgi-stroke hgi-fire-security"></i> Hardware Firewalls: getting-online/hardware/firewall/index.md
    - Software:
      - <i class="hgi-stroke hgi-computer-cloud"></i> Virtual Private Networks: getting-online/software/virtual-private-networks/index.md
  - <i class="hgi-stroke hgi-wrench-01"></i> Private Devices:
    - <i class="hgi-stroke hgi-smartphone-wifi"></i> Smartphone: devices/smart-phone/index.md
  - Backup Methods:
    - <i class="hgi-stroke hgi-hard-drive"></i> Hardware Encrypted Drives: managing-credentials/options/hardware-encrypted-usb-drives/index.md
  - Credential Management:
    - <i class="hgi-stroke hgi-lock-key"></i> Hardware Security Keys: managing-credentials/options/hardware-keys/index.md
    - <i class="hgi-stroke hgi-circle-password"></i> Password Managers:  managing-credentials/options/password-managers/home.md
extra_css:
  - assets/css/navigation.css
  - assets/css/content.css
  - assets/css/footer.css
  - https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - https://cdn.materialdesignicons.com/6.4.95/css/materialdesignicons.min.css
  - https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css
  - https://cdn.jsdelivr.net/npm/@primer/octicons@latest/dist/octicons.css
  - https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css
  - https://cdn.hugeicons.com/font/hgi-stroke-rounded.css
extra_javascript:
  - assets/js/open-in-new-tab.js
markdown_extensions:
  - footnotes # Enable footnotes under Markdown
  - toc: # Settings for Sidebar Options
      permalink: false
      toc_depth: 4
  # Media Captions
  - pymdownx.blocks.caption # https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/caption/

  # Insert Tags
  - pymdownx.caret # https://facelessuser.github.io/pymdown-extensions/extensions/caret/

  # Mark Tags - Highlighting
  - pymdownx.mark # https://facelessuser.github.io/pymdown-extensions/extensions/mark/
  
  # Delete Tag - Deleting
  - pymdownx.tilde # https://facelessuser.github.io/pymdown-extensions/extensions/tilde/

  # Critic Changes
  - pymdownx.critic # https://facelessuser.github.io/pymdown-extensions/extensions/critic/
  
  # Details - Note Boxes 
  - pymdownx.details # https://facelessuser.github.io/pymdown-extensions/extensions/details/

  # Emoji Support
  - pymdownx.emoji: # https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg