site_name: Knowledge Base
site_url: https://sitename.example
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.instant.progress # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=breadcrumbs#progress-indicator
    - navigation.instant.preview # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=breadcrumbs#automatic-previews
    - navigation.sections # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    - navigation.tracking # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=breadcrumbs#anchor-tracking
    - navigation.prune # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=breadcrumbs#navigation-pruning
    - navigation.top # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=breadcrumbs#back-to-top-button
  font: 
    text: Quicksand
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  plugins:
    - search
    - material-extensions
nav:
  - <i class="hgi-stroke hgi-book-open-01"></i> Start Here:
    - <i class="hgi-stroke hgi-favourite"></i> Welcome: start-here/index.md
    - <i class="hgi-stroke hgi-book-open-02"></i> Glossary: glossary/index.md
    - <i class="hgi-stroke hgi-edit-01"></i> Design Guide: start-here/style-guide.md
  - <i class="hgi-stroke hgi-connect"></i> Home Networking:
    - <i class="hgi-stroke hgi-home-wifi"></i> Service Providers: home-networking/service-providers/index.md
    - <i class="hgi-stroke hgi-computer-phone-sync"></i> Networking Equipment: home-networking/networking/index.md
  - <i class="hgi-stroke hgi-tv-01"></i> Physical Devices:
    - <i class="hgi-stroke hgi-smartphone-wifi"></i> Smartphone: physical-devices/android-phone/index.md
    - <i class="hgi-stroke hgi-stroke hgi-computer"></i> Desktop Computer: physical-devices/desktop-computer/index.md
  - <i class="hgi-stroke hgi-wireless-cloud-access"></i> Software:
    - <i class="hgi-stroke hgi-geometric-shapes-01"></i> Tools: getting-online/software/index.md
  - <i class="hgi-stroke hgi-user"></i> Digital Accounts:
    - <i class="hgi-stroke hgi-authorized"></i> Authentication: digital-accounts/authentication/index.md
extra_css:
  - assets/css/dark-theme/dark-markdown.css
  - assets/css/dark-theme/navigation.css
  - assets/css/dark-theme/footer.css
  - assets/css/light-theme/light-markdown.css
  - assets/css/light-theme/navigation.css
  - https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - https://cdn.materialdesignicons.com/6.4.95/css/materialdesignicons.min.css
  - https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css
  - https://cdn.jsdelivr.net/npm/@primer/octicons@latest/dist/octicons.css
  - https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css
  - https://cdn.hugeicons.com/font/hgi-stroke-rounded.css
  - https://use.fontshare.com/css/aesthetic.cs
extra_javascript:
  - assets/js/open-in-new-tab.js
markdown_extensions:
  - footnotes # Enable footnotes under Markdown
  - toc: # Settings for Sidebar Options
      permalink: false
      toc_depth: 4
  # Media Captions
  - pymdownx.blocks.caption # https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/caption/

  # Insert Tags
  - pymdownx.caret # https://facelessuser.github.io/pymdown-extensions/extensions/caret/

  # Mark Tags - Highlighting
  - pymdownx.mark # https://facelessuser.github.io/pymdown-extensions/extensions/mark/
  
  # Delete Tag - Deleting
  - pymdownx.tilde # https://facelessuser.github.io/pymdown-extensions/extensions/tilde/

  # Critic Changes
  - pymdownx.critic # https://facelessuser.github.io/pymdown-extensions/extensions/critic/
  
  # Details - Note Boxes 
  - pymdownx.details # https://facelessuser.github.io/pymdown-extensions/extensions/details/

  # Emoji Support
  - pymdownx.emoji: # https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg