site_name: Knowledge Base
site_url: https://sitename.example
theme:
  name: material
  font: 
    text: Comfortaa
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/w
  palette:
    scheme: slate
  plugins:
    - typeset

nav:
  
  - Start Here: index.md
  
  - Getting Online:
    - <i class="hgi-stroke hgi-satellite-01"></i> Service Providers: getting-online/service-providers/index.md
    - Routers:
      - Operating Systems:
        - OpenWRT: getting-online/routers/operating-systems/openwrt/index.md
      - Proposed Models: getting-online/routers/proposed-models/index.md
    - Virtual Private Networks:
      - Providers: getting-online/virtual-private-networks/providers/index.md
  - Devices:
    - <i class="hgi-stroke hgi-smartphone-wifi"></i> Smartphone:
      - <i class="hgi-stroke hgi-shopping-bag-03"></i> Choosing a Device Model: docs/devices/android/choosing-a-device/phone#1.md
      - <i class="hgi-stroke hgi-simcard-01"></i> Subscriber ID Module (SIM): 
        - Providers: docs/devices/android/deciding-on-a-sim/providers/index.md
        - Types: docs/devices/android/deciding-on-a-sim/types/index.md
      - <i class="hgi-stroke hgi-layers-02"></i> Operating System:
        - <i class="fa-brands fa-android"></i> GrapheneOS: docs/devices/android/choosing-an-operating-system/grapheneos.md
      - <i class="hgi-stroke hgi-grid-view"></i> Applications:
        - <i class="hgi-stroke hgi-sparkles"></i> Core Device Functionality:
          - <i class="fa-brands fa-google-play"></i> Application Stores: docs/devices/android/applications/core-device-functionality/application-stores/index.md
          - <i class="hgi-stroke hgi-copy-link"></i> Browser: docs/devices/android/applications/core-device-functionality/browser/index.md
          - <i class="hgi-stroke hgi-calendar-03"></i> Calendar: docs/devices/android/applications/calendar/index.md
          - <i class="hgi-stroke hgi-alarm-clock"></i> Clock & Alarm: docs/devices/android/applications/core-device-functionality/clock-alarm/index.md
          - <i class="hgi-stroke hgi-contact-02"></i> Contacts Management: docs/devices/android/applications/core-device-functionality/contact-management/index.md
          - <i class="hgi-stroke hgi-folder-01"></i> File Manager: docs/devices/android/applications/core-device-functionality/file-manager/index.md
          - <i class="hgi-stroke hgi-keyboard"></i> Keyboard: docs/devices/android/applications/core-device-functionality/keyboard/index.md
          - <i class="hgi-stroke hgi-dashboard-square-edit"></i> Launcher: docs/devices/android/applications/core-device-functionality/launcher/index.md
          - <i class="hgi-stroke hgi-call-ringing-04"></i> Phone: docs/devices/android/applications/core-device-functionality/phone/index.md
          - <i class="hgi-stroke hgi-mail-add-02"></i> Text Messaging: docs/devices/android/applications/core-device-functionality/sms-messaging/index.md   
        - <i class="hgi-stroke hgi-security-check"></i> Device Security:
          - <i class="hgi-stroke hgi-test-tube-01"></i> Antivirus: docs/devices/android/applications/device-security/malware-scanner/index.md
          - <i class="hgi-stroke hgi-delivery-box-01"></i> Application Manager: docs/devices/android/applications/device-security/application-manager/index.md
          - <i class="hgi-stroke hgi-geometric-shapes-01"></i> Background Activities: docs/devices/android/applications/device-security/background-activities-management/index.md
          - <i class="hgi-stroke hgi-firewall"></i> Firewall: docs/devices/android/applications/device-security/firewall-client/index.md
          - <i class="hgi-stroke hgi-legal-01"></i> Permission Manager: docs/devices/android/applications/device-security/permission-manager/index.md
          - <i class="hgi-stroke hgi-pacman-01"></i> Tracker Protection: docs/devices/android/applications/device-security/tracker-protection/index.md
          - <i class="hgi-stroke hgi-cloud-server"></i> Virtual Private Network Clients (VPNs): docs/devices/android/applications/device-security/virtual-private-network-client/index.md
          - <i class="hgi-stroke hgi-clean"></i> System Cleaner: docs/devices/android/applications/device-security/system-cleaner/index.md
          - <i class="hgi-stroke hgi-suit-01"></i> Work Profile: docs/devices/android/applications/device-security/work-profile/index.md
        - <i class="hgi-stroke hgi-tools"></i> System Maintenance:
          - <i class="hgi-stroke hgi-database-sync-01"></i> Backup & Recovery: docs/devices/android/applications/system-maintenance/backup-recovery/index.md
          - <i class="hgi-stroke hgi-eraser"></i> Free-Space Eraser: docs/devices/android/applications/system-maintenance/free-space-eraser/index.md
        - <i class="hgi-stroke hgi-playlist-02"></i> Media Playback:
          - <i class="hgi-stroke hgi-audio-book-03"></i> Audiobooks: docs/devices/android/applications/media-access/audiobooks/index.md
          - <i class="hgi-stroke hgi-book-open-02"></i> Book Readers: docs/devices/android/applications/media-access/book-readers/index.md
          - <i class="hgi-stroke hgi-folder-file-storage"></i> File Viewer: docs/devices/android/applications/media-access/file-viewer/graphene-viewer.md
          - <i class="hgi-stroke hgi-music-note-03"></i> Music Player: docs/devices/android/applications/media-access/music-players/index.md
          - <i class="hgi-stroke hgi-google-photos"></i> Photo Gallery: docs/devices/android/applications/media-access/photo-gallery
          - <i class="hgi-stroke hgi-airpod-03"></i> Podcasts: docs/devices/android/applications/media-access/podcasts/antennapod.md
          - <i class="hgi-stroke hgi-flim-slate"></i> Video Player: docs/devices/android/applications/media-access/video-players/index.md
        - <i class="hgi-stroke hgi-checkmark-badge-04"></i> Social Media:
          - <i class="hgi-stroke hgi-quill-write-02"></i> Micro-blogging:
            - BlueSky: docs/devices/android/applications/social-media/categories/micro-blogging/bluesky.md
            - Mastradon: docs/devices/android/applications/social-media/categories/micro-blogging/mastradon.md
          - <i class="hgi-stroke hgi-ai-image"></i> Visual Content:
            - <i class="hgi-stroke hgi-instagram"></i> Instagram: docs/devices/android/applications/social-media/categories/picture-sharing/instagram.md
          - <i class="hgi-stroke hgi-tv-01"></i> Video Publishing:
            - <i class="hgi-stroke hgi-youtube"></i> YouTube: docs/devices/android/applications/social-media/categories/video-sharing/youtube.md
        - <i class="hgi-stroke hgi-comment-01"></i> Communication:
          - <i class="hgi-stroke hgi-message-multiple-02"></i> Private Messaging:
            - <i class="hgi-stroke hgi-signal"></i> Signal: docs/devices/android/applications/private-messaging/signal.md
          - <i class="hgi-stroke hgi-mail-at-sign-01"></i> Email Clients:
            - FairEmail: docs/devices/android/applications/email-clients/fairmail.md
            - ProtonMail: docs/devices/android/applications/email-clients/protonmail.md
            - Thunderbird: docs/devices/android/applications/email-clients/thunderbird.md
            - Tutanota: docs/devices/android/applications/email-clients/tutanota.md
        - <i class="hgi-stroke hgi-credit-card-pos"></i> Credential Management:
          - <i class="hgi-stroke hgi-square-lock-password"></i> Password Managers:
            - Bitwarden: docs/devices/android/applications/password-management/bitwarden.md
          - Two-Factor Authentication:
            - Aegis: docs/devices/android/applications/two-factor-authentication/aegis.md
            - Yubico Authenticator: docs/devices/android/applications/two-factor-authentication/yubico.md
        - <i class="hgi-stroke hgi-notification-02"></i> Notification Management: docs/devices/android/applications/notification-management/buzz-kill.md
        - <i class="hgi-stroke hgi-edit-01"></i> Notes: docs/devices/android/applications/notes/index.md
        - <i class="hgi-stroke hgi-file-validation"></i> Metadata Manipulation: docs/devices/android/applications/metadata-manipulation/index.md
        - <i class="hgi-stroke hgi-maps-search"></i> Navigation & Maps: docs/devices/android/applications/navigation-and-maps/index.md
      - System Settings:
        - Developer Options: docs/devices/android/system-settings/developer-options/index.md
  - Online Accounts:
    - Account Creation:
      - <i class="hgi-stroke hgi-mail-at-sign-01"></i> Email: docs/online-accounts/creating/email.md
      - <i class="hgi-stroke hgi-user"></i> Username: docs/online-accounts/creating/usernames.md
      - <i class="hgi-stroke hgi-lock-key"></i> Passwords: docs/online-accounts/creating/passwords.md
      - <i class="hgi-stroke hgi-signal-medium-01"></i> Phone Numbers: docs/online-accounts/creating/phone-numbers.md
      - <i class="hgi-stroke hgi-database-import"></i> Personal Information: docs/online-accounts/creating/personal-info.md
    - Authentication Methods:
      - Passwordless Authentication:
        - Passkeys: online-accounts/authenticating/passwordless-authentication/passkeys.md
      - Two-Factor (2FA) Authentication:
        - <i class="hgi-stroke hgi-command"></i> Authentication Apps: docs/online-accounts/authenticating/two-factor-authentication/methods/authenticator-apps.md
        - <i class="iconoir-mail"></i> Email Verification: docs/online-accounts/authenticating/two-factor-authentication/methods/email-links.md
        - <i class="fa-solid fa-fingerprint"></i> Hardware Keys: docs/online-accounts/authenticating/two-factor-authentication/methods/hardware-keys.md
        - <i class="mdi mdi-key-chain-variant"></i> Password Managers: docs/online-accounts/authenticating/two-factor-authentication/methods/password-managers.md
        - <i class="iconoir-app-notification"></i> Push Notifications: docs/online-accounts/authenticating/two-factor-authentication/methods/push-notifications.md
        - <i class="iconoir-chat-lines"></i> SMS Authentication: docs/online-accounts/authenticating/two-factor-authentication/methods/sms-authentication.md
  - Managing Credentials:
    - <i class="hgi-stroke hgi-hard-drive"></i> Hardware Encrypted Drives: managing-credentials/options/hardware-encrypted-usb-drives/index.md
    - <i class="mdi mdi-onepassword"></i> Hardware Security Keys: managing-credentials/options/hardware-keys/index.md
    - Password Managers:
      - Bitwarden: managing-credentials/options/password-managers/bitwarden.md
extra_css:
  - css/main.css
  - https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - https://cdn.materialdesignicons.com/6.4.95/css/materialdesignicons.min.css
  - https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css
  - https://cdn.jsdelivr.net/npm/@primer/octicons@latest/dist/octicons.css
  - https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css
  - https://cdn.hugeicons.com/font/hgi-stroke-rounded.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption
